# -*- coding: utf-8 -*-
"""Dimension Reduction

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14VOEsPTE0JsjP0upUsdz3OSq1BzubNbk
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings("ignore")
# %matplotlib inline
import matplotlib
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
#read data from given xls
from google.colab import drive
drive.mount('/gdrive')
# %cd /gdrive
!ls
# %cd MyDrive
m_data = pd.read_csv('data.csv')
# string karakterlerin int e cevrilmesi
encoder = LabelEncoder()
# Tum sutunlar icin uygulama
for col in m_data.columns:
    m_data[col] = encoder.fit_transform(m_data[col])

X_features = m_data.iloc[:,1:23]
y_label = m_data.iloc[:, 0]

#Feature ölceklendirme
scaler = StandardScaler()
X_features = scaler.fit_transform(X_features)

#Görselleştirme
pca = PCA()
pca.fit_transform(X_features)
pca_variance = pca.explainedvariance

plt.figure(figsize=(8, 6))
plt.bar(range(22), pca_variance, alpha=0.5, align='center', label='individual variance')
plt.legend()
plt.ylabel('Variance ratio')
plt.xlabel('Principal components')
plt.show()

pca2 = PCA(n_components=17)
pca2.fit(X_features)
x_3d = pca2.transform(X_features)
plt.figure(figsize=(8,6))
plt.scatter(x_3d[:,0], x_3d[:,5], c=m_data['class'])
plt.show()

pca3 = PCA(n_components=2)
pca3.fit(X_features)
x_3d = pca3.transform(X_features)
plt.figure(figsize=(8,6))
plt.scatter(x_3d[:,0], x_3d[:,1], c=m_data['class'])
plt.show()