# -*- coding: utf-8 -*-
"""Outliers Detection

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14VOEsPTE0JsjP0upUsdz3OSq1BzubNbk
"""

# Commented out IPython magic to ensure Python compatibility.
import seaborn as sns
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")
# %matplotlib inline
import numpy as np
# %matplotlib inline
###########################
#read data from given csv
from google.colab import drive
drive.mount('/gdrive')
!ls
data = pd.read_csv('data.csv')
###########################
import seaborn as sns
len = len(data.columns)
for i in len:
    sns.boxplot(x=data.columns[i])
    Q1 = data.Puan.quantile(0.25)
    Q2 = data.Puan.quantile(0.5)
    Q3 = data.Puan.quantile(0.75)
    Q4 = data.Puan.quantile(1)
    IQR = Q3 - Q1

    print("Q1-->", Q1)
    print("Q3-->", Q3)
    print("Q2-->", Q2)
    print("Q4-->", Q4)
    print("IQR-->", IQR)
    print("Alt sınır: Q1 - 1.5 * IQR--->", Q1 - 1.5 * IQR)
    print("Üst sınır: Q3 + 1.5 * IQR--->", Q3 + 1.5 * IQR)
    outliers_data = data[(data.Puan < Q1 - 1.5 * IQR) or (data.Puan > Q3 + 1.5 * IQR)]
    print (outliers_data)
############################